// @ts-nocheck
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.112.4";
const SB_URL=Deno.env.get("SUPABASE_URL")??"",V5=`${SB_URL}/functions/v1/ciao-core-api-fast-v5`;
const ALLOWED_ORIGINS=new Set(["https://godievda-pixel.github.io","https://ciao-web-app.orderly-bulb.workers.dev","https://ciao-web-app.ciao-web.workers.dev"]);
function serviceKey(){const s=Deno.env.get("SUPABASE_SECRET_KEYS");if(s){try{const j=JSON.parse(s);if(typeof j?.default==="string")return j.default;const x=Object.values(j??{}).find(v=>typeof v==="string");if(x)return String(x)}catch{}}return Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??""}
const db=createClient(SB_URL,serviceKey(),{auth:{persistSession:false}});
function cors(req){const origin=req.headers.get("origin")??"";return{"access-control-allow-origin":ALLOWED_ORIGINS.has(origin)?origin:"https://godievda-pixel.github.io","access-control-allow-methods":"GET,POST,OPTIONS","access-control-allow-headers":"content-type,x-telegram-init-data","access-control-max-age":"86400","vary":"Origin"}}
const out=(req,x,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors(req),"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
async function proxy(req,b){const r=await fetch(V5,{method:"POST",headers:{"content-type":"application/json","x-telegram-init-data":req.headers.get("x-telegram-init-data")??""},body:JSON.stringify(b)}),j=await r.json().catch(()=>({}));return{r,j}}
function telegramId(req){try{const p=new URLSearchParams(req.headers.get("x-telegram-init-data")??""),u=JSON.parse(p.get("user")??"null");return Number(u?.id)||0}catch{return 0}}
function team(t){return t?{id:Number(t.id),name:String(t.name??""),short_name:t.short_name??null,custom_emoji_id:t.custom_emoji_id??null}:null}
function normalize(m){return{match_id:Number(m.id),id:Number(m.id),kickoff_at:m.kickoff_at??null,nominal_date:m?.round?.nominal_date??null,round_number:m?.round?.number??null,home:team(m.home),away:team(m.away),home_score:m.home_score??null,away_score:m.away_score??null,is_finished:!!m.is_finished,live_status:m.live_status??null,live_elapsed:m.live_elapsed??null,live_phase:m.live_phase??null}}
function scheduleTs(m){const exact=Date.parse(String(m?.kickoff_at||''));if(Number.isFinite(exact))return exact;const nominal=Date.parse(String(m?.nominal_date||''));return Number.isFinite(nominal)?nominal+12*3600000:Number.POSITIVE_INFINITY}
function resultForTeam(m,teamId){const home=Number(m?.home?.id)===Number(teamId),gf=Number(home?m?.home_score:m?.away_score),ga=Number(home?m?.away_score:m?.home_score);return gf>ga?'W':gf<ga?'L':'D'}
function withoutRoundBonus(payload){if(!payload||typeof payload!=="object")return payload;if(payload.rules&&typeof payload.rules==="object")payload.rules={...payload.rules,bonus_multiplier:1,bonus_per_round:0,bonus_enabled:false};if(payload.round_summary&&typeof payload.round_summary==="object")payload.round_summary={...payload.round_summary,bonus_selected:false,bonus_locked:true};payload.round_bonus={match_id:null,selected_at:null,updated_at:null,locked:true,can_choose:false,can_move:false,available_match_ids:[],disabled:true,removed:true};return payload}
async function eagerFavorite(req){const tid=telegramId(req);if(!tid)return null;const uq=await db.from("cp_users").select("favorite_team_id").eq("telegram_id",tid).maybeSingle();if(uq.error||!uq.data?.favorite_team_id)return null;const id=Number(uq.data.favorite_team_id);const [tq,mq]=await Promise.all([db.from("cp_teams").select("id,name,short_name,custom_emoji_id").eq("id",id).maybeSingle(),db.from("cp_matches").select("id,kickoff_at,home_score,away_score,is_finished,live_status,live_elapsed,live_phase,round:cp_rounds!cp_matches_round_fk(number,nominal_date),home:cp_teams!cp_matches_home_team_fk(id,name,short_name,custom_emoji_id),away:cp_teams!cp_matches_away_team_fk(id,name,short_name,custom_emoji_id)").or(`home_team_id.eq.${id},away_team_id.eq.${id}`).order("round_id",{ascending:true})]);if(tq.error||mq.error||!tq.data)return null;const all=(mq.data??[]).map(normalize),finished=all.filter(x=>x.is_finished).sort((a,b)=>scheduleTs(b)-scheduleTs(a)),upcoming=all.filter(x=>!x.is_finished).sort((a,b)=>scheduleTs(a)-scheduleTs(b));const form=finished.slice(0,5).map(m=>({result:resultForTeam(m,id),match_id:m.id,home_team:m.home?.name??null,away_team:m.away?.name??null,home_score:m.home_score,away_score:m.away_score,kickoff_at:m.kickoff_at,nominal_date:m.nominal_date??null}));return{ok:true,team:team(tq.data),coverage:{overview:true},overview:{form,last_match:finished[0]??null,next_match:upcoming[0]??null}}}
Deno.serve(async req=>{try{if(req.method==="OPTIONS")return new Response("ok",{headers:cors(req)});if(req.method==="GET")return out(req,{ok:true,service:"Ciao Core API Fast v6",version:6,eager_favorite:true,nominal_date_fallback:true,round_bonus:false,cors_origins:[...ALLOWED_ORIGINS]});if(req.method!=="POST")return new Response("Method Not Allowed",{status:405,headers:cors(req)});const b=await req.json().catch(()=>({})),action=String(b.action??"state");if(action==="set_round_bonus")return out(req,{ok:false,error:"Бонус x2 удалён из правил",code:"bonus_removed"},410);if(action!=="state"){const x=await proxy(req,b);if(action==="prediction_rules"&&x.j?.rules)x.j.rules={...x.j.rules,bonus_multiplier:1,bonus_per_round:0,bonus_enabled:false};return out(req,x.j,x.r.status)}const baseP=proxy(req,b),favP=eagerFavorite(req).catch(()=>null),[base,favorite]=await Promise.all([baseP,favP]);if(!base.r.ok||!base.j?.ok)return out(req,base.j,base.r.status);withoutRoundBonus(base.j);if(favorite)base.j.favorite_club_profile=favorite;return out(req,base.j,base.r.status)}catch(e){console.error("core_v6_error",e);return out(req,{ok:false,error:e instanceof Error?e.message:String(e)},500)}});
