import { createApiClient } from './api.js';
import { formatMoney, unitAccent, buildEmployeePayload, buildIncomePayload, buildExpensePayload } from './logic.js';

const root = document.querySelector('#app');
const tg = window.Telegram?.WebApp;
try { tg?.ready(); tg?.expand(); tg?.setHeaderColor?.('#070809'); tg?.setBackgroundColor?.('#070809'); } catch {}

const state = {
  admin: null,
  unit: 'moscow',
  page: 'home',
  month: new Date().toISOString().slice(0,7),
  dashboard: null,
  employees: [],
  events: [],
  refs: null,
};

const initData = tg?.initData || '';
const api = createApiClient({ baseUrl: '', initData });
const unitNames = { moscow:'Москва', spb:'Петербург', regions:'Регионы', staff:'Штат' };
const pageNames = { home:'Финансы', events:'Ивенты', employees:'Сотрудники', operations:'Операции', reports:'Отчёты' };
const employeeTypeNames = { staff:'Штатный', event:'Ивентный', both:'Штатный + Ивентный' };

function esc(v=''){return String(v).replace(/[&<>"']/g,(m)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));}
function monthLabel(value){const [y,m]=value.split('-').map(Number);return new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(new Date(y,m-1,1)).toUpperCase();}
function initials(name){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();}
function today(){return new Date().toISOString().slice(0,10);}
function optionList(rows, valueKey='id', labelKey='name', selected=''){return `<option value="">—</option>${rows.map(x=>`<option value="${esc(x[valueKey])}" ${String(x[valueKey])===String(selected)?'selected':''}>${esc(x[labelKey])}</option>`).join('')}`;}
function toast(text){let el=document.querySelector('.toast');if(!el){el=document.createElement('div');el.className='toast';document.body.append(el);}el.textContent=text;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800);}
function showError(message){const el=document.querySelector('#sheetError');if(el){el.textContent=message;el.hidden=false;}else toast(message);}
function navButton(page, icon, label){return `<button class="nav ${state.page===page?'active':''}" data-page="${page}"><i>${icon}</i>${label}</button>`;}

function shell(content){
  document.documentElement.style.setProperty('--accent', unitAccent(state.unit));
  return `<div class="shell"><header class="top"><div class="brand-row"><div class="brand">КВИЗ ПЛЮС</div><div class="admin">${esc(state.admin?.displayName || 'Админ')}</div></div><div class="title-row"><div class="page-title">${pageNames[state.page]}</div><div class="period">${monthLabel(state.month)}</div></div><div class="units">${Object.entries(unitNames).map(([code,name])=>`<button class="unit-btn ${state.unit===code?'active':''}" data-unit="${code}">${name}</button>`).join('')}</div></header><main>${content}</main><button class="fab" data-action="quick">＋</button><nav class="bottom">${navButton('home','⌂','Финансы')}${navButton('events','▣','Ивенты')}${navButton('employees','◉','Сотрудники')}${navButton('reports','▥','Отчёты')}${navButton('operations','•••','Ещё')}</nav></div>`;
}

function dashboardView(){const d=state.dashboard||{};return `<div class="hero"><div class="eyebrow">Чистая прибыль</div><div class="hero-value">${formatMoney(d.profit)}</div><div class="hero-sub">${unitNames[state.unit]} • фактические операции за месяц</div></div><div class="rule"></div><div class="pnl-grid"><div class="pnl"><small>Доходы</small><b>${formatMoney(d.grossIncome)}</b><span>чистыми ${formatMoney(d.netIncome)}</span></div><div class="pnl"><small>Расходы</small><b>${formatMoney((d.expenses||0)+(d.payroll||0))}</b><span>ФОТ ${formatMoney(d.payroll)}</span></div><div class="pnl"><small>К выплате</small><b>${formatMoney(d.toPay)}</b><span>баланс сотрудников</span></div><div class="pnl"><small>Налоги</small><b>${formatMoney(d.tax)}</b><span>по доходам с налогом</span></div></div><div class="section-title">Управление периодом</div><div class="feed"><div class="feed-icon">◀</div><div class="feed-main"><b>${monthLabel(state.month)}</b><span>Переключай месяц без изменения данных</span></div><div class="month-nav"><button data-month="prev">‹</button><button data-month="next">›</button></div></div><div class="section-title">Система</div><div class="feed"><div class="feed-icon">▦</div><div class="feed-main"><b>Google Sheets</b><span>Контур подготовлен, синхронизация будет следующим этапом</span></div><div class="feed-side">БД</div></div>`;}
function eventsView(){if(state.unit==='staff')return `<div class="empty">Штатные начисления живут вне ивентов и городов.<br>Выбери Москву, Петербург или Регионы.</div>`;return `<button class="primary-line" data-action="new-event">Создать новый ивент <span>＋</span></button><div class="section-title">Мероприятия</div>${state.events.length?state.events.map(e=>`<div class="event"><div class="event-head"><div><div class="event-title">${esc(e.title)}</div><div class="event-meta">${esc(e.eventDate)} • ${unitNames[e.unitCode]||esc(e.unitCode)}</div></div><div class="event-type">P&L</div></div><div class="event-grid"><div><small>Доход</small><b>${formatMoney(e.grossIncome)}</b></div><div><small>Расход</small><b>${formatMoney((e.payroll||0)+(e.expenses||0))}</b></div><div><small>Прибыль</small><b class="profit">${formatMoney(e.profit)}</b></div></div></div>`).join(''):`<div class="empty">В этом разделе пока нет ивентов.</div>`}`;}
function employeeList(rows){return rows.length?rows.map(e=>`<div class="person"><div class="avatar">${initials(e.fullName)}</div><div class="person-main"><div class="person-name">${esc(e.fullName)}</div><div class="person-meta">${employeeTypeNames[e.employeeType]||esc(e.employeeType)}${e.organizationRole?` • ${esc(e.organizationRole)}`:''}</div></div><div class="balance"><b class="${e.balanceDue<0?'advance':''}">${formatMoney(e.balanceDue)}</b><span>${e.balanceDue<0?'аванс':'к выплате'}</span></div></div>`).join(''):`<div class="empty">Сотрудников пока нет.</div>`;}
function employeesView(){return `<button class="primary-line" data-action="new-employee">Добавить сотрудника <span>＋</span></button><input class="search" id="employeeSearch" placeholder="Поиск сотрудника"><div id="employeeList">${employeeList(state.employees)}</div>`;}
function operationsView(){return `<div class="quick-grid"><button class="quick income" data-action="new-income">Доход<em>с налогом или без</em></button><button class="quick expense" data-action="new-expense">Расход<em>организация / компенсация</em></button><button class="quick accrual" data-action="new-accrual">Начисление<em>зарплата / бонус</em></button><button class="quick payment" data-action="new-payment">Выплата<em>FIFO + аванс</em></button></div><div class="section-title">Логика выплат</div><div class="feed"><div class="feed-icon">₽</div><div class="feed-main"><b>Старые начисления закрываются первыми</b><span>Переплата автоматически становится авансом на будущие начисления.</span></div></div><div class="feed"><div class="feed-icon">!</div><div class="feed-main"><b>Удаления нет</b><span>Финансовые операции только аннулируются с обязательным комментарием.</span></div></div>`;}
function reportsView(){const due=state.employees.filter(x=>x.balanceDue>0).reduce((s,x)=>s+x.balanceDue,0);const advances=Math.abs(state.employees.filter(x=>x.balanceDue<0).reduce((s,x)=>s+x.balanceDue,0));const eventProfit=state.events.reduce((s,x)=>s+(x.profit||0),0);return `<div class="report"><div class="report-num">01</div><div class="report-main"><b>К выплате сотрудникам</b><span>${formatMoney(due)}</span></div></div><div class="report"><div class="report-num">02</div><div class="report-main"><b>Авансы сотрудников</b><span>${formatMoney(advances)}</span></div></div><div class="report"><div class="report-num">03</div><div class="report-main"><b>Прибыль показанных ивентов</b><span>${formatMoney(eventProfit)}</span></div></div><div class="report"><div class="report-num">04</div><div class="report-main"><b>Журнал изменений</b><span>Аудит ведётся в Supabase и не зависит от интерфейса</span></div></div>`;}

function render(){let view='';if(state.page==='home')view=dashboardView();if(state.page==='events')view=eventsView();if(state.page==='employees')view=employeesView();if(state.page==='operations')view=operationsView();if(state.page==='reports')view=reportsView();root.innerHTML=shell(view);bind();}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;render();loadPage();});document.querySelectorAll('[data-unit]').forEach(b=>b.onclick=()=>{state.unit=b.dataset.unit;render();loadPage();});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));document.querySelectorAll('[data-month]').forEach(b=>b.onclick=()=>changeMonth(b.dataset.month));const search=document.querySelector('#employeeSearch');if(search)search.oninput=()=>{const q=search.value.toLowerCase();document.querySelector('#employeeList').innerHTML=employeeList(state.employees.filter(x=>x.fullName.toLowerCase().includes(q)));};}
function changeMonth(direction){const [y,m]=state.month.split('-').map(Number);const d=new Date(Date.UTC(y,m-1+(direction==='next'?1:-1),1));state.month=`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;render();loadDashboard();}

async function loadDashboard(){try{state.dashboard=await api.get(`/api/qpf/dashboard?month=${state.month}&unit=${state.unit}`);render();}catch(e){toast(errorText(e));}}
async function loadEmployees(){try{state.employees=await api.get('/api/qpf/employees');render();}catch(e){toast(errorText(e));}}
async function loadEvents(){if(state.unit==='staff'){state.events=[];render();return;}try{state.events=await api.get(`/api/qpf/events?unit=${state.unit}`);render();}catch(e){toast(errorText(e));}}
async function loadPage(){if(state.page==='home')return loadDashboard();if(state.page==='employees')return loadEmployees();if(state.page==='events')return loadEvents();if(state.page==='reports'){await Promise.all([loadEmployees(),loadEvents()]);render();}}
function errorText(e){const code=e?.message||'';return ({telegram_init_data_required:'Открой приложение из Telegram',telegram_auth_invalid:'Telegram-авторизация не прошла',admin_access_denied:'Нет доступа администратора'}[code]||'Не удалось выполнить операцию');}

function openSheet(title, body){closeSheet();const overlay=document.createElement('div');overlay.className='overlay show';overlay.id='overlay';overlay.onclick=closeSheet;const sheet=document.createElement('div');sheet.className='sheet open';sheet.id='sheet';sheet.innerHTML=`<div class="sheet-title">${title}</div><div id="sheetError" class="error" hidden></div>${body}`;document.body.append(overlay,sheet);sheet.querySelectorAll('[data-close]').forEach(x=>x.onclick=closeSheet);}
function closeSheet(){document.querySelector('#overlay')?.remove();document.querySelector('#sheet')?.remove();}
function formValue(form,name){const el=form.elements[name];return el?.type==='checkbox'?el.checked:el?.value;}
function formShell(fields, submitText='Сохранить'){return `<form id="dataForm">${fields}<div class="form-actions"><button type="button" class="btn" data-close>Отмена</button><button class="btn primary" type="submit">${submitText}</button></div></form>`;}
function action(name){if(name==='quick')return quickSheet();if(name==='new-employee')return employeeForm();if(name==='new-event')return eventForm();if(name==='new-income')return incomeForm();if(name==='new-expense')return expenseForm();if(name==='new-accrual')return accrualForm();if(name==='new-payment')return paymentForm();}
function quickSheet(){openSheet('Быстрое действие',`<div class="sheet-grid"><button data-go="new-income">＋ Доход</button><button data-go="new-expense">＋ Расход</button><button data-go="new-accrual">＋ Начисление</button><button data-go="new-payment">＋ Выплата</button><button data-go="new-event">＋ Ивент</button><button data-go="new-employee">＋ Сотрудник</button></div>`);document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>action(b.dataset.go));}

function employeeForm(){const orgRoles=(state.refs?.roles||[]).filter(r=>r.scope==='organization'||r.scope==='both');openSheet('Новый сотрудник',formShell(`<div class="field"><label>Имя</label><input name="fullName" required></div><div class="field"><label>Тип сотрудника</label><select name="employeeType"><option value="staff">Штатный</option><option value="event">Ивентный</option><option value="both">Штатный + Ивентный</option></select></div><div class="field"><label>Роль в организации</label><select name="organizationRoleId">${optionList(orgRoles)}</select></div><div class="field-row"><div class="field"><label>Телефон</label><input name="phone"></div><div class="field"><label>Telegram</label><input name="telegramUsername" placeholder="@username"></div></div><div class="field"><label>Комментарий</label><textarea name="notes"></textarea></div>`));document.querySelector('#dataForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await api.post('/api/qpf/employees',buildEmployeePayload({fullName:formValue(f,'fullName'),employeeType:formValue(f,'employeeType'),organizationRoleId:formValue(f,'organizationRoleId'),phone:formValue(f,'phone'),telegramUsername:formValue(f,'telegramUsername'),notes:formValue(f,'notes')}));closeSheet();toast('Сотрудник добавлен');await loadEmployees();}catch(err){showError(errorText(err));}};}

function eventForm(){const types=state.refs?.eventTypes||[];const cities=state.refs?.regionCities||[];const defaultUnit=state.unit==='staff'?'moscow':state.unit;openSheet('Новый ивент',formShell(`<div class="field"><label>Название</label><input name="title" required></div><div class="field"><label>Тип мероприятия</label><select name="eventTypeId" required>${optionList(types)}</select></div><div class="field-row"><div class="field"><label>Городской контур</label><select name="unitCode"><option value="moscow" ${defaultUnit==='moscow'?'selected':''}>Москва</option><option value="spb" ${defaultUnit==='spb'?'selected':''}>Петербург</option><option value="regions" ${defaultUnit==='regions'?'selected':''}>Регионы</option></select></div><div class="field"><label>Региональный город</label><select name="regionCityId">${optionList(cities)}</select></div></div><div class="field-row"><div class="field"><label>Дата</label><input type="date" name="eventDate" value="${today()}" required></div><div class="field"><label>Начало</label><input type="time" name="startTime"></div></div><div class="field"><label>Площадка</label><input name="venue"></div><div class="field"><label>Комментарий</label><textarea name="notes"></textarea></div>`));document.querySelector('#dataForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const unitCode=formValue(f,'unitCode');try{await api.post('/api/qpf/events',{title:formValue(f,'title').trim(),eventTypeId:formValue(f,'eventTypeId'),unitCode,regionCityId:formValue(f,'regionCityId')||null,eventDate:formValue(f,'eventDate'),startTime:formValue(f,'startTime')||null,endTime:null,venue:formValue(f,'venue')||null,notes:formValue(f,'notes')||null});closeSheet();toast('Ивент создан');state.unit=unitCode;await loadEvents();}catch(err){showError(errorText(err));}};}

function incomeForm(){const refs=state.refs||{};const events=state.events||[];openSheet('Новый доход',formShell(`<div class="field"><label>Сумма</label><input type="number" min="0" step="0.01" name="grossAmount" required></div><div class="field"><label>Источник</label><select name="sourceId">${optionList(refs.incomeSources||[])}</select></div><div class="field"><label>Ивент</label><select name="eventId">${optionList(events,'id','title')}</select></div><div class="field-row"><div class="field"><label>Дата</label><input type="date" name="incomeDate" value="${today()}" required></div><div class="field"><label>Способ оплаты</label><select name="paymentMethodId">${optionList(refs.paymentMethods||[])}</select></div></div><div class="field-row"><label class="check"><input type="checkbox" name="taxEnabled" checked> Учитывать налог</label><div class="field"><label>Ставка, %</label><input type="number" name="taxRate" value="9" step="0.01"></div></div><div class="field"><label>Комментарий</label><textarea name="description"></textarea></div>`,'Добавить доход'));document.querySelector('#dataForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await api.post('/api/qpf/incomes',buildIncomePayload({eventId:formValue(f,'eventId'),unitCode:state.unit==='staff'?'moscow':state.unit,sourceId:formValue(f,'sourceId'),description:formValue(f,'description'),grossAmount:formValue(f,'grossAmount'),taxEnabled:formValue(f,'taxEnabled'),taxRate:formValue(f,'taxRate'),incomeDate:formValue(f,'incomeDate'),paymentMethodId:formValue(f,'paymentMethodId')}));closeSheet();toast('Доход добавлен');await loadDashboard();}catch(err){showError(errorText(err));}};}

function expenseForm(){const refs=state.refs||{};openSheet('Новый расход',formShell(`<div class="field"><label>Сумма</label><input type="number" min="0" step="0.01" name="amount" required></div><div class="field"><label>Категория</label><select name="categoryId">${optionList(refs.expenseCategories||[])}</select></div><div class="field"><label>Тип расхода</label><select name="expenseKind"><option value="organization">Расход организации</option><option value="employee_reimbursement">Оплатил сотрудник — компенсировать</option></select></div><div class="field"><label>Сотрудник для компенсации</label><select name="paidByEmployeeId">${optionList(state.employees,'id','fullName')}</select></div><div class="field-row"><div class="field"><label>Дата</label><input type="date" name="expenseDate" value="${today()}" required></div><div class="field"><label>Способ оплаты</label><select name="paymentMethodId">${optionList(refs.paymentMethods||[])}</select></div></div><div class="field"><label>Комментарий</label><textarea name="description"></textarea></div>`,'Добавить расход'));document.querySelector('#dataForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;const kind=formValue(f,'expenseKind');if(kind==='employee_reimbursement'&&!formValue(f,'paidByEmployeeId'))return showError('Выбери сотрудника для компенсации');try{await api.post('/api/qpf/expenses',buildExpensePayload({eventId:null,unitCode:state.unit,categoryId:formValue(f,'categoryId'),description:formValue(f,'description'),expenseKind:kind,amount:formValue(f,'amount'),expenseDate:formValue(f,'expenseDate'),paymentMethodId:formValue(f,'paymentMethodId'),paidByEmployeeId:formValue(f,'paidByEmployeeId')}));closeSheet();toast('Расход добавлен');await Promise.all([loadDashboard(),loadEmployees()]);}catch(err){showError(errorText(err));}};}

function accrualForm(){openSheet('Новое начисление',formShell(`<div class="field"><label>Сотрудник</label><select name="employeeId" required>${optionList(state.employees,'id','fullName')}</select></div><div class="field"><label>Тип начисления</label><select name="accrualType"><option value="monthly_salary">Зарплата за месяц</option><option value="bonus">Бонус</option><option value="adjustment">Корректировка</option><option value="other">Другое</option></select></div><div class="field-row"><div class="field"><label>Сумма</label><input type="number" min="0" step="0.01" name="amount" required></div><div class="field"><label>Дата</label><input type="date" name="accruedOn" value="${today()}" required></div></div><div class="field"><label>Описание</label><textarea name="description"></textarea></div>`,'Начислить'));document.querySelector('#dataForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await api.post('/api/qpf/accruals',{employeeId:formValue(f,'employeeId'),unitCode:state.unit,accrualType:formValue(f,'accrualType'),description:formValue(f,'description')||null,amount:Number(formValue(f,'amount')),accruedOn:formValue(f,'accruedOn')});closeSheet();toast('Начисление создано');await Promise.all([loadEmployees(),loadDashboard()]);}catch(err){showError(errorText(err));}};}

function paymentForm(){const refs=state.refs||{};openSheet('Новая выплата',formShell(`<div class="field"><label>Сотрудник</label><select name="employeeId" required>${optionList(state.employees,'id','fullName')}</select></div><div class="field-row"><div class="field"><label>Сумма</label><input type="number" min="0" step="0.01" name="amount" required></div><div class="field"><label>Дата</label><input type="date" name="paidOn" value="${today()}" required></div></div><div class="field"><label>Способ оплаты</label><select name="paymentMethodId">${optionList(refs.paymentMethods||[])}</select></div><div class="field"><label>Комментарий</label><textarea name="description"></textarea></div>`,'Выплатить'));document.querySelector('#dataForm').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget;try{await api.post('/api/qpf/payments',{employeeId:formValue(f,'employeeId'),amount:Number(formValue(f,'amount')),paidOn:formValue(f,'paidOn'),paymentMethodId:formValue(f,'paymentMethodId')||null,description:formValue(f,'description')||null});closeSheet();toast('Выплата проведена');await Promise.all([loadEmployees(),loadDashboard()]);}catch(err){showError(errorText(err));}};}

async function bootstrap(){if(!initData){root.innerHTML=`<div class="gate"><div><b>Квиз Плюс • Финансы</b><p>Открой Mini App из Telegram. Финансовые данные доступны только разрешённым администраторам.</p></div></div>`;return;}try{const session=await api.post('/api/qpf/session',{});state.admin=session.admin||session;state.refs=await api.get('/api/qpf/references');const [employees,events,dashboard]=await Promise.all([api.get('/api/qpf/employees'),api.get(`/api/qpf/events?unit=${state.unit}`),api.get(`/api/qpf/dashboard?month=${state.month}&unit=${state.unit}`)]);state.employees=employees;state.events=events;state.dashboard=dashboard;render();}catch(e){root.innerHTML=`<div class="gate"><div><b>Доступ закрыт</b><p>${esc(errorText(e))}</p></div></div>`;}}
bootstrap();
